docker_users: 
  - vagrant

# Docker version
docker_edition: 'ce'
# docker-{{ docker_edition }}: '18.06'


kubernetes_allow_pods_on_master: false

kubernetes_version: '1.17'
kubernetes_version_rhel_package: '1.17.2'
# kubernetes_packages:
#   - name: kubelet=1.17.2-00
#     state: present
#   - name: kubectl=1.17.2-00
#     state: present
#   - name: kubeadm=1.17.2-00
#     state: present
#   - name: kubernetes-cni=0.8.5-0
#     state: present

# kubernetes_kubelet_extra_args: "--node-ip=10.0.2.15"

kubernetes_yum_arch: x86_64

# kubernetes_pod_network_cidr: '10.244.0.0/16'
kubernetes_apiserver_advertise_address: '192.168.2.110'
kubernetes_version_kubeadm: 'stable-{{ kubernetes_version }}'

kubernetes_ignore_preflight_errors: 'all'
