- hosts: all

  vars:
    kubernetes_allow_pods_on_master: False
  
  pre_tasks:
    - name: Disable Swap
      shell: "swapoff -a"
      ignore_errors: True

  roles:
    - docker
    - kubernetes

  tasks:
    - include: include/docker/config.yml
