- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Reset Kubernetes component
      shell: "kubeadm reset --force"
      ignore_errors: True

    - name: Reset iptables
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X

    - name: Set bridge
      shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
   ## - name: Delete flannel.1 interface
   ##   command: ip link delete flannel.1
   ##   when: network == "flannel"
   ##   ignore_errors: True

   ## - name: Delete cni0 interface
   ##   command: ip link delete cni0
   ##   when: network == "flannel"
   ##   ignore_errors: True
