# kubectl run nginx --image=nginx:1.7.12
# kubectl get replicasets --selector=run=nginx
# kubectl scale deployments nginx --replicas=2


# kubectl get deployments nginx --export -o yaml > nginx-deployment.yaml
# kubectl replace -f nginx-deployment.yaml --save-config // Replace the existing nginx deployment
# kubectl create -f ????


apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: nginx
  name: nginx
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
      metadata:
  #     annotations:
  #       kubernetes.io/change-cause: "Update nginx to 1.9.10"
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      containers:
      - image: nginx:1.7.12
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}